### ISSUE TITLE
TypeError: Cannot read property "source" from undefined. (line 57, file "Code")

### ISSUE THREAD

**Issue by yujinchung** [pratik0809/GSheetsToMailchimp#3]
Hi, I am trying to use your codes to manage mailchimp lists in a way more effective and tried the script you wrote but, I had this error. `TypeError: Cannot read property "source" from undefined. (line 57, file "Code")`. Do you have any advices on how to improve this?

**Comment by pratik0809** [comment]
@yujinchung are you trying to run the script? This script is automatically triggered when the active sheet is edited and will throw an error if you attempt to manually run it.  See this stackoverflow thread for more info: https://stackoverflow.com/questions/40743876/typeerror-cannot-read-property-source-from-undefined-line-7-file-code

Let me know if this answers your question
